  export const belts = [
    {
      id: 101,
      name: 'Classic Italian Leather Belt',
      price: 149,
      originalPrice: 199,
      image: 'https://images.pexels.com/photos/1598505/pexels-photo-1598505.jpeg',
      category: 'Formal Belt',
      rating: 5,
      material: 'Italian Leather',
      width: '35mm',
    },
    {
      id: 102,
      name: 'Executive Brown Leather Belt',
      price: 129,
      originalPrice: 179,
      image: 'https://images.pexels.com/photos/1598506/pexels-photo-1598506.jpeg',
      category: 'Business Belt',
      rating: 5,
      material: 'Premium Leather',
      width: '32mm',
    },
    {
      id: 103,
      name: 'Luxury Crocodile Pattern Belt',
      price: 199,
      originalPrice: 249,
      image: 'https://images.pexels.com/photos/1598509/pexels-photo-1598509.jpeg',
      category: 'Luxury Belt',
      rating: 5,
      material: 'Crocodile Leather',
      width: '38mm',
    },
    {
      id: 104,
      name: 'Vintage Cognac Leather Belt',
      price: 139,
      originalPrice: 189,
      image: 'https://images.pexels.com/photos/1598510/pexels-photo-1598510.jpeg',
      category: 'Casual Belt',
      rating: 4,
      material: 'Vintage Leather',
      width: '35mm',
    },
    {
      id: 105,
      name: 'Premium Black Dress Belt',
      price: 159,
      originalPrice: 209,
      image: 'https://images.pexels.com/photos/1598511/pexels-photo-1598511.jpeg',
      category: 'Formal Belt',
      rating: 5,
      material: 'Calf Leather',
      width: '30mm',
    },
    {
      id: 106,
      name: 'Handcrafted Tan Belt',
      price: 169,
      originalPrice: 219,
      image: 'https://images.pexels.com/photos/1598512/pexels-photo-1598512.jpeg',
      category: 'Artisan Belt',
      rating: 5,
      material: 'Hand-stitched Leather',
      width: '35mm',
    },
  ];
