export const products = [
    {
      id: 1,
      name: 'Oxford Elegance Classic',
      price: 299,
      originalPrice: 399,
      image: 'https://images.pexels.com/photos/292999/pexels-photo-292999.jpeg',
      category: 'Formal',
      rating: 5,
    },
    {
      id: 2,
      name: 'Venetian Oxford Style',
      price: 349,
      originalPrice: 449,
      image: 'https://images.pexels.com/photos/267301/pexels-photo-267301.jpeg',
      category: 'Formal',
      rating: 5,
    },
    {
      id: 3,
      name: 'Classic Gentleman Oxford',
      price: 279,
      originalPrice: 379,
      image: 'https://images.pexels.com/photos/298863/pexels-photo-298863.jpeg',
      category: 'Formal',
      rating: 4,
    },
    {
      id: 4,
      name: 'Premium Italian Leather',
      price: 429,
      originalPrice: 529,
      image: 'https://images.pexels.com/photos/1599004/pexels-photo-1599004.jpeg',
      category: 'Formal',
      rating: 5,
    },
    {
      id: 5,
      name: 'Modern Derby Classic',
      price: 259,
      originalPrice: 359,
      image: 'https://images.pexels.com/photos/2529148/pexels-photo-2529148.jpeg',
      category: 'Casual',
      rating: 4,
    },
    {
      id: 6,
      name: 'Executive Wingtip Oxford',
      price: 389,
      originalPrice: 489,
      image: 'https://images.pexels.com/photos/1598507/pexels-photo-1598507.jpeg',
      category: 'Formal',
      rating: 5,
    },
    {
      id: 7,
      name: 'Executive Wingtip ',
      price: 389,
      originalPrice: 489,
      image: 'https://images.pexels.com/photos/1598507/pexels-photo-1598507.jpeg',
      category: 'Formal',
      rating: 5,
    }
  ];