export const CLINIC = {
  name: "Cherish Derma Clinic",
  tagline: "care. heal. glow",
  statement: "Where Expertise Meets Confidence",
  doctor: "Dr. Snehal Karape",
  doctorTitle: "MD Dermatology | Founder & Chief Dermatologist",
  doctorBio:
    "With over 12 years of clinical expertise in advanced dermatology, Dr. Snehal Karape combines medical precision with an aesthetic eye to deliver transformative results. Her patient-first philosophy ensures every treatment is personalised, ethical, and evidence-based.",
  phone: "+91 98765 43210",
  email: "hello@cherishdermaclinic.com",
  address: "123, Luxury Medical Complex, Koregaon Park, Pune – 411001",
  map: "https://maps.google.com",
  whatsapp: "https://wa.me/919876543210",
  instagram: "https://instagram.com/cherishdermaclinic",
  facebook: "https://facebook.com/cherishdermaclinic",
  hours: [
    { day: "Mon – Sat", time: "10:00 AM – 7:00 PM" },
    { day: "Sunday", time: "By Appointment Only" },
  ],
};

export const STATS = [
  { value: 1000, suffix: "+", label: "Happy Patients" },
  { value: 12, suffix: "+", label: "Years Experience" },
  { value: 30, suffix: "+", label: "Advanced Treatments" },
  { value: 96, suffix: "%", label: "Patient Satisfaction" },
];

export const WHY_CHOOSE = [
  {
    icon: "stethoscope",
    title: "Doctor-Led Care",
    desc: "Every treatment is personally designed and supervised by Dr. Snehal Karape — never delegated.",
  },
  {
    icon: "sparkles",
    title: "Personalised Treatment",
    desc: "No cookie-cutter protocols. Your skin is unique; your treatment plan is too.",
  },
  {
    icon: "zap",
    title: "Advanced Technology",
    desc: "US-FDA approved lasers, USFDA cleared devices, and evidence-based protocols.",
  },
  {
    icon: "heart",
    title: "Ethical Dermatology",
    desc: "We recommend only what you need. No upselling, no unnecessary procedures.",
  },
];

export const Treatments = [
  {
    id: "hair-regrowth-prp",
    title: "Hair Regrowth & PRP",
    category: "Hair",
    shortDesc: "Restore thickness, density and confidence with science-backed regenerative therapy.",
    benefits: ["Stimulates dormant follicles", "PRP rich growth factors", "GFC Therapy available", "Zero downtime"],
    featured: true,
   
  },
  {
    id: "acne-treatment",
    title: "Acne Treatment",
    category: "Skin",
    shortDesc: "Clear skin, clear confidence. Advanced acne management from root cause to scar revision.",
    benefits: ["Active acne control", "Hormonal acne therapy", "Scar revision", "LED & Chemical peels"],
    featured: true,
    
  },
  {
    id: "pigmentation-treatment",
    title: "Pigmentation Treatment",
    category: "Skin",
    shortDesc: "Reveal even-toned, luminous skin with targeted depigmentation protocols.",
    benefits: ["Melasma management", "Dark spot reduction", "Q-Switch laser", "Chemical peels"],
    featured: true,
    emoji: "✦",
  },
  {
    id: "anti-ageing",
    title: "Anti-Ageing",
    category: "Skin",
    shortDesc: "Turn back time naturally. Volumize, lift and rejuvenate with luxury anti-ageing solutions.",
    benefits: ["Botox & Fillers", "Thread lift", "Skin boosters", "RF Microneedling"],
    featured: false,
    emoji: "✧",
  },
  {
    id: "laser-hair-reduction",
    title: "Laser Hair Reduction",
    category: "Laser",
    shortDesc: "Permanent smoothness with painless diode and Nd:YAG laser technology.",
    benefits: ["All skin types", "USFDA cleared lasers", "Quick sessions", "Long-lasting results"],
    featured: false,
    emoji: "✧",
  },
  {
    id: "skin-rejuvenation",
    title: "Skin Rejuvenation",
    category: "Skin",
    shortDesc: "Hydrated, glowing, youthful skin — restored from within.",
    benefits: ["HydraFacial", "Meso therapy", "Exosome therapy", "Glow protocols"],
    featured: false,
    emoji: "✧",
  },
  {
    id: "exosome-therapy",
    title: "Exosome Therapy",
    category: "Advanced",
    shortDesc: "Next-generation regenerative therapy for hair and skin at the cellular level.",
    benefits: ["Cellular regeneration", "Hair density boost", "Skin repair", "Clinically validated"],
    featured: false,
    emoji: "✧",
  },
  {
    id: "bridal-programs",
    title: "Bridal Programs",
    category: "Programs",
    shortDesc: "Glow on your most important day. Bespoke bridal skin & hair journeys.",
    benefits: ["3–6 month program", "Head-to-toe glow", "Personalised protocol", "Dedicated care team"],
    featured: false,
    emoji: "✧",
  },
  {
    id: "mens-skin-hair",
    title: "Men's Skin & Hair",
    category: "Men",
    shortDesc: "Modern grooming meets medical excellence for the discerning gentleman.",
    benefits: ["Hair loss solutions", "Beard growth", "Acne management", "Anti-ageing for men"],
    featured: false,
    emoji: "✧",
  },
];

export const PROGRAMS = [
  {
    id: "acne-to-confidence",
    title: "Acne to Confidence",
    subtitle: "Program",
    duration: "3 Months",
    tagline: "From breakouts to breakthrough.",
    desc: "A medically guided 12-week journey that addresses root causes of acne—hormonal, dietary, lifestyle—while restoring skin texture and rebuilding your confidence.",
    steps: [
      { week: "Wk 1–2", label: "Skin Analysis & Root Cause Mapping" },
      { week: "Wk 3–6", label: "Active Acne Control Protocol" },
      { week: "Wk 7–10", label: "Scar Revision & Tone Correction" },
      { week: "Wk 11–12", label: "Maintenance & Glow Protocol" },
    ],
    color: "from-terracotta/10 to-cream",
    image: "/programs/acne-program.jpg",
  },
  {
    id: "hair-recovery",
    title: "Hair Recovery",
    subtitle: "Program",
    duration: "4 Months",
    tagline: "Reclaim your crown.",
    desc: "A comprehensive 16-week hair restoration program combining PRP, GFC, Exosomes, and scalp nutrition protocols to reverse thinning and restore density.",
    steps: [
      { week: "Wk 1–2", label: "Scalp & Hair Health Assessment" },
      { week: "Wk 3–8", label: "Regenerative Treatment Cycle" },
      { week: "Wk 9–14", label: "Growth Activation Phase" },
      { week: "Wk 15–16", label: "Maintenance & Nutrition Plan" },
    ],
    color: "from-forest/10 to-cream",
    image: "/programs/hair-program.jpg",
  },
  {
    id: "corporate-skin-confidence",
    title: "Corporate Skin Confidence",
    subtitle: "Program",
    duration: "6 Weeks",
    tagline: "Look as sharp as your ambitions.",
    desc: "A results-driven, time-efficient skin program for busy professionals — targeting pigmentation, fatigue, and stress-related skin concerns.",
    steps: [
      { week: "Wk 1", label: "Professional Skin Assessment" },
      { week: "Wk 2–3", label: "Rapid Brightening Protocol" },
      { week: "Wk 4–5", label: "Anti-Fatigue & Glow Treatments" },
      { week: "Wk 6", label: "Maintenance Ritual Education" },
    ],
    color: "from-sand/20 to-cream",
    image: "/programs/corporate-program.jpg",
  },
  {
    id: "mens-skin-hair",
    title: "Men's Skin & Hair",
    subtitle: "Program",
    duration: "3 Months",
    tagline: "Confidence is the new power suit.",
    desc: "India's first luxury men's dermatology program — addressing hair loss, beard grooming, acne, and anti-ageing in a discreet, modern setting.",
    steps: [
      { week: "Wk 1–2", label: "Complete Skin & Hair Analysis" },
      { week: "Wk 3–6", label: "Hair & Beard Restoration" },
      { week: "Wk 7–10", label: "Skin Clarity & Anti-Ageing" },
      { week: "Wk 11–12", label: "Grooming Mastery & Home Care" },
    ],
    color: "from-forest/10 to-cream",
    image: "/programs/mens-program.jpg",
  },
  {
    id: "bridal-confidence",
    title: "Bridal Confidence",
    subtitle: "Program",
    duration: "6 Months",
    tagline: "Glow on your most beautiful day.",
    desc: "The most comprehensive bridal skin & hair program in Pune — starting 6 months before the big day for a transformative, photo-ready glow.",
    steps: [
      { week: "Mo 1–2", label: "Baseline Assessment & Foundation Protocols" },
      { week: "Mo 3–4", label: "Pigmentation, Acne & Hair Intensive" },
      { week: "Mo 5", label: "Brightening & Contouring Treatments" },
      { week: "Mo 6", label: "Final Glow Protocol & Skin Prep" },
    ],
    color: "from-terracotta/10 to-cream",
    image: "/programs/bridal-program.jpg",
  },
];

export const TESTIMONIALS = [
  {
    name: "Priya S.",
    location: "Koregaon Park, Pune",
    text: "I've tried multiple clinics before, but Cherish Derma is in a different league. Dr. Snehal's approach is incredibly thorough — she found the root cause of my melasma when others didn't. After 3 months of treatment, my skin is the clearest it's been in years.",
    rating: 5,
    treatment: "Pigmentation Treatment",
  },
  {
    name: "Rahul M.",
    location: "Baner, Pune",
    text: "Skeptical about hair loss clinics — but Cherish Derma completely changed my perspective. The PRP + GFC combination they designed for me showed results by month 2. Dr. Snehal explains everything so clearly. Worth every penny.",
    rating: 5,
    treatment: "Hair Regrowth Program",
  },
  {
    name: "Sneha D.",
    location: "Aundh, Pune",
    text: "The Bridal Confidence Program was the best investment I made for my wedding. 5 months in and my skin transformed completely. I didn't need heavy makeup on my big day because my skin was glowing on its own.",
    rating: 5,
    treatment: "Bridal Confidence Program",
  },
  {
    name: "Aditya K.",
    location: "Viman Nagar, Pune",
    text: "As a corporate professional, I needed efficient results. The Corporate Skin Confidence program was exactly that. No fluff, just results. My colleagues keep asking what changed. I'd never felt this confident in meetings.",
    rating: 5,
    treatment: "Corporate Skin Confidence",
  },
];

export const SERVICE_OPTIONS = [
  "Hair Regrowth & PRP",
  "Acne Treatment",
  "Pigmentation Treatment",
  "Anti-Ageing",
  "Laser Hair Reduction",
  "Skin Rejuvenation",
  "Exosome Therapy",
  "Bridal Program",
  "Men's Skin & Hair",
  "General Consultation",
];

export const TIME_SLOTS = [
  "10:00 AM",
  "10:30 AM",
  "11:00 AM",
  "11:30 AM",
  "12:00 PM",
  "12:30 PM",
  "2:00 PM",
  "2:30 PM",
  "3:00 PM",
  "3:30 PM",
  "4:00 PM",
  "4:30 PM",
  "5:00 PM",
  "5:30 PM",
  "6:00 PM",
  "6:30 PM",
];

export const CORE_VALUES = [
  {
    icon: "heart",
    title: "Compassion",
    desc: "Every patient walks in with a story. We listen before we treat.",
  },
  {
    icon: "award",
    title: "Excellence",
    desc: "We settle for nothing less than the best evidence-based outcomes.",
  },
  {
    icon: "shield",
    title: "Integrity",
    desc: "Honest advice, ethical protocols, no unnecessary procedures.",
  },
  {
    icon: "user",
    title: "Personalisation",
    desc: "No two skins are alike. Neither are our treatment plans.",
  },
];

export const ACHIEVEMENTS = [
  { number: "1000+", label: "Patients Treated" },
  { number: "12+", label: "Years of Excellence" },
  { number: "30+", label: "Advanced Technologies" },
  { number: "96%", label: "Patient Satisfaction" },
  { number: "50+", label: "Bridal Glow Stories" },
  { number: "200+", label: "Hair Recovery Success Cases" },
];

export const BLOG_POSTS = [
  {
    id: "understanding-hair-loss",
    slug: "understanding-hair-loss",
    title: "Understanding Hair Loss: Causes, Types & Modern Treatments",
    excerpt: "Hair loss affects millions of Indians, yet most don't know the real cause. Hormones, nutrition, genetics — here's what dermatologists want you to know before you self-diagnose.",
    category: "Hair Care",
    date: "June 10, 2026",
    readTime: "5 min read",
    image: "https://images.unsplash.com/photo-1522337360826-0a3fc7cf9dba?auto=format&fit=crop&w=900&q=80",
    featured: true,
    author: "Dr. Snehal Karape",
  },
  {
    id: "skincare-ingredients-dermatologists-recommend",
    slug: "skincare-ingredients-dermatologists-recommend",
    title: "5 Skincare Ingredients That Dermatologists Actually Recommend",
    excerpt: "The beauty industry is full of overhyped ingredients. We cut through the noise and highlight what clinical evidence actually supports for radiant, healthy skin.",
    category: "Skincare",
    date: "May 28, 2026",
    readTime: "4 min read",
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=900&q=80",
    featured: false,
    author: "Dr. Snehal Karape",
  },
  {
    id: "laser-hair-reduction-what-to-expect",
    slug: "laser-hair-reduction-what-to-expect",
    title: "Laser Hair Reduction: What to Expect Before, During & After",
    excerpt: "Thinking about permanent hair removal but unsure what the process involves? This guide covers everything from skin type suitability to session frequency and results timeline.",
    category: "Laser",
    date: "May 15, 2026",
    readTime: "6 min read",
    image: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=900&q=80",
    featured: false,
    author: "Dr. Snehal Karape",
  },
  {
    id: "bridal-skincare-timeline",
    slug: "bridal-skincare-timeline",
    title: "Bridal Skincare Timeline: 6 Months to Glowing on Your Wedding Day",
    excerpt: "Great bridal skin doesn't happen overnight. Here's the month-by-month roadmap our dermatologist recommends to ensure you look absolutely radiant on your big day.",
    category: "Bridal",
    date: "May 2, 2026",
    readTime: "7 min read",
    image: "https://images.unsplash.com/photo-1594736797933-d0e20b17d530?auto=format&fit=crop&w=900&q=80",
    featured: false,
    author: "Dr. Snehal Karape",
  },
  {
    id: "acne-vs-purging",
    slug: "acne-vs-purging",
    title: "Acne vs. Purging: How to Tell the Difference (and What to Do)",
    excerpt: "Started a new skincare product and seeing more breakouts? Before you panic and throw it away, learn to distinguish between skin purging and a genuine adverse reaction.",
    category: "Acne",
    date: "April 20, 2026",
    readTime: "4 min read",
    image: "https://images.unsplash.com/photo-1512290923902-8a9f81dc236c?auto=format&fit=crop&w=900&q=80",
    featured: false,
    author: "Dr. Snehal Karape",
  },
  {
    id: "prp-therapy-for-hair",
    slug: "prp-therapy-for-hair",
    title: "PRP Therapy for Hair: The Science Behind the Trend",
    excerpt: "Platelet-Rich Plasma therapy has become one of the most sought-after treatments for hair loss. But does the science back the hype? Our dermatologist explains what PRP can and cannot do.",
    category: "Hair Care",
    date: "April 8, 2026",
    readTime: "5 min read",
    image: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=900&q=80",
    featured: false,
    author: "Dr. Snehal Karape",
  },
  {
    id: "anti-ageing-treatments-guide",
    slug: "anti-ageing-treatments-guide",
    title: "Anti-Ageing Treatments Explained: Botox, Fillers & RF Microneedling",
    excerpt: "With so many anti-ageing procedures available today, choosing the right one can be overwhelming. Here's a plain-language breakdown of the most effective options and who they're best suited for.",
    category: "Anti-Ageing",
    date: "March 25, 2026",
    readTime: "6 min read",
    image: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&w=900&q=80",
    featured: false,
    author: "Dr. Snehal Karape",
  },
  {
    id: "men-skincare-guide",
    slug: "men-skincare-guide",
    title: "The Modern Man's Guide to Skincare: Where to Start",
    excerpt: "Skincare isn't gender-specific — but men's skin has unique characteristics. From choosing the right cleanser to addressing beard-related skin issues, here's everything you need.",
    category: "Lifestyle",
    date: "March 10, 2026",
    readTime: "4 min read",
    image: "https://images.unsplash.com/photo-1612817288484-6f916006741a?auto=format&fit=crop&w=900&q=80",
    featured: false,
    author: "Dr. Snehal Karape",
  },
];
